DELETE FROM project;
DELETE FROM evaluator;
DELETE FROM supervisor;
DELETE FROM executive;
DELETE FROM programm;
DELETE FROM researcher;
DELETE FROM organisation;
DELETE FROM deliverable;
DELETE FROM phone;
DELETE FROM research_centre;
DELETE FROM university;
DELETE FROM company;
DELETE FROM researcher_in_project;
DELETE FROM scientific_field;
DELETE FROM project_scientific_field;
ALTER TABLE project AUTO_INCREMENT = 1;
ALTER TABLE researcher AUTO_INCREMENT = 1;
ALTER TABLE organisation AUTO_INCREMENT = 1;
ALTER TABLE supervisor AUTO_INCREMENT = 1;
ALTER TABLE evaluator AUTO_INCREMENT = 1;
ALTER TABLE executive AUTO_INCREMENT = 1;
ALTER TABLE programm AUTO_INCREMENT = 1;
ALTER TABLE scientific_field AUTO_INCREMENT = 1;